#include gconvert.cl #type0 char
#include gconvert.cl #type0 uchar
#include gconvert.cl #type0 short
#include gconvert.cl #type0 ushort
#include gconvert.cl #type0 int
#include gconvert.cl #type0 uint
#include gconvert.cl #type0 long
#include gconvert.cl #type0 ulong
#include gconvert.cl #type0 float
#include gconvert.cl #type0 double
#include gconvert.cl #type0 half